Repository ghoshnirmalya/nextjs-strapi-boilerplate, pull requests merged in 2020-08, with the labels that each got.

#2 Use Apollo for GraphQL
  frontend/components/pages/feeds/add-new-feed-form.tsx
  frontend/components/pages/feeds/index.tsx
  frontend/components/pages/index/index.tsx
  frontend/components/pages/my-account/index.tsx
  frontend/lib/with-graphql.tsx
  frontend/package.json
  frontend/yarn.lock
  readme.md
Labels: enhancement

#3 Update readme.md file
  readme.md
Labels: enhancement

#5 Update readme.md file
  frontend/.env.example
  frontend/lib/with-graphql.tsx
  frontend/pages/api/auth/[...nextauth].ts
  readme.md
Labels: documentation

#6 fix: remove '/graphql' from env NEXT_PUBLIC_API_URL
  frontend/.env.example
  readme.md
Labels: bug
